### ISSUE TITLE
license discrepancy

### ISSUE THREAD

**Issue by onlyjob** [xtingray/tupi#12]
`README.md` contains the following: 
`Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved.`

But there is no copyright notice in `README.md`...

This note seems unnecessary as Tupi is under GPL-2+ terms and of course there is a conflict with last statement of this file: `See the file COPYING for copying conditions.`.

**Comment by xtingray** [comment]
Fixed in the devel version. Thank you for the feedback! :)
