### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by bedna-KU** [xtingray/tupi#15]
In INSTALL.md is dependency on qt4 and compilation throw this error:
./configure --prefix=/usr/local/tupi
- Checking for Qt >= 5.4.0
- Testing for qmake... /home/mario/bin/tupi/qonf/qmake.rb:56: warning: Insecure world writable dir /home/mario/bin in PATH, mode 040777
  [ FAILED ]
- Configure failed. error was: Invalid Qt version.
  Please, upgrade to 5.4.0 or higher (Visit: http://qt-project.org)

**Comment by xtingray** [comment]
Sorry, very old documentation. The file has been updated to point the official wiki section for developers -> http://www.maefloresta.com/wiki/doku.php?id=developer_resources
